# Generated by Django 3.1.6 on 2021-03-07 12:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('addedAt', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 7, 12, 14, 8, 208303, tzinfo=utc), null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('categoryFrom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoryFrom', to='api.category')),
                ('categoryTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoryTo', to='api.category')),
            ],
        ),
    ]
