# Generated by Django 3.1.6 on 2021-03-07 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210307_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='bi bi-file', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='addedAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 7, 13, 51, 56, 49054, tzinfo=utc), null=True),
        ),
    ]
