# Generated by Django 3.1.6 on 2021-03-03 19:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210303_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('addedAt', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 3, 19, 27, 52, 781511, tzinfo=utc), null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wallet')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='addedAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 3, 19, 27, 52, 781182, tzinfo=utc), null=True),
        ),
        migrations.DeleteModel(
            name='Paymant',
        ),
    ]
