# Generated by Django 3.1.6 on 2021-03-05 21:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210303_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_from', to='api.category'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to', to='api.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='addedAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 5, 21, 10, 49, 978591, tzinfo=utc), null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
